ci:
  skip: [pylint]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
        exclude: ^.idea/
      - id: trailing-whitespace
      - id: pretty-format-json
        args: [ "--no-sort-keys", "--autofix", "--indent=4" ]
        exclude: ^.vscode/
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.292
    hooks:
      - id: ruff
        args: ["--fix"]
        exclude: "tests/input/"
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==23.9.1
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-use-type-annotations
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
      - id: text-unicode-replacement-char
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.6.0
  #   hooks:
  #     - id: mypy
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: bash -c 'test -d .venv && . .venv/bin/activate ; pylint "$@"' -
        language: system
        types: [ python ]
        args: ["-sn", "-rn"]
