---
ci:
  skip: [pylint]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        exclude: ^.idea/
      - id: trailing-whitespace
      - id: pretty-format-json
        exclude: ^.vscode/
        args:
          - --autofix
          - --no-sort-keys
          - --indent=4
      - id: check-yaml
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-shebang-scripts-are-executable
      - id: name-tests-test
        exclude: ^tests/(input/|base_tester(|_test).py$)
        args:
          - --pytest-test-first
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args:
          - --mapping
          - '2'
          - --sequence
          - '4'
          - --offset
          - '2'
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.1
    hooks:
      - id: ruff
        args:
          - --fix
        exclude: tests/input/
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.18.0
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==23.9.1
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-use-type-annotations
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
      - id: text-unicode-replacement-char
  - repo: local
    hooks:
      - id: python-no-log-fatal
        name: avoid logger.fatal(
        description: A quick check for the deprecated `.fatal()` method of python loggers
        entry: (?<!warnings)\.fatal\(
        language: pygrep
        types: [python]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
      - id: mypy
        exclude: tests/input/
        additional_dependencies:
          - pylint
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: bash -c 'test -d .venv && . .venv/bin/activate ; pylint "$@"' -
        language: system
        types: [python]
        args:
          - -sn
          - -rn
